"""
Django settings for xnote project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['DEBUG'] == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'sebastianczech-xnote.herokuapp.com'
]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'app.apps.AppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathfilters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xnote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xnote.wsgi.application'


# # Import local settings
# local_settings = False
# try:
#     from notes.local import use_sql_lite
#     local_settings = use_sql_lite
# except ImportError as e:
#     pass


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# # production database on Heroku used on Heroku and local machines (but not for tests)
# if 'test' not in sys.argv and local_settings is False:
#     # PostgreSQL on Heroku
#     # DATABASES['default'] =  dj_database_url.config()
#     # PostgreSQL on Linuxpl.com
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': os.environ['PG_USER'],
#             'USER': os.environ['PG_USER'],
#             'PASSWORD': os.environ['PG_PASSWORD'],
#             'HOST': os.environ['PG_HOST'],
#             'PORT': '5432',
#         }
#     }
# # default local SQLite used on local machine for tests
# else:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Mongo
MONGO_DB_URI = 'mongodb+srv://' + os.environ['MONGO_USER'] + ':' + os.environ['MONGO_PASSWORD'] + '@' + os.environ['MONGO_HOST'] + '?retryWrites=true&w=majority&ssl=true&ssl_cert_reqs=CERT_NONE'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'collectstatic')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Append slash to URL
APPEND_SLASH = True

# URLs for login and subsite
FORCE_SCRIPT_NAME = '/'
SUB_SITE = '/'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Google OAuth2 settings
GOOGLE_OAUTH2_CLIENT_SECRETS_JSON = 'client_secret.json'
GOOGLE_OAUTH2_SCOPE = 'https://www.googleapis.com/auth/calendar'
GOOGLE_OAUTH2_SCOPES = ['https://www.googleapis.com/auth/calendar']
GOOGLE_OAUTH2_LOCAL_SERVER_PORT = 8484
GOOGLE_OAUTH2_TOKEN_FILE = 'token.json'
if 'runserver' not in sys.argv:
    GOOGLE_OAUTH2_REDIRECT_URL = 'https://sebastianczech-notes.herokuapp.com/oauth2callback'
    GOOGLE_OAUTH2_LOCAL_SERVER = 'sebastianczech-notes.herokuapp.com'
else:
    GOOGLE_OAUTH2_REDIRECT_URL = 'http://localhost:8000/oauth2callback'
    GOOGLE_OAUTH2_LOCAL_SERVER = 'localhost'